_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 48
                - 53
                - 54
                - 79
                - 106
            "2":
                - 1
                - 5
                - 41
                - 48
                - 53
                - 54
                - 79
                - 106
            "3":
                - 1
                - 2
                - 14
                - 55
                - 62
            "4": 3.10.13
            "5": 0.20.1
            "12": 0.20.1
            "13": darwin-x86_64
epochs:
    value: 20
l1:
    value: 10
l3:
    value: 1
l4:
    value: 0.01
l5:
    value: 0.01
