program: main.py
name: sweeptest1234
method: random
metric:
  goal: maximize
  name: RQS
parameters:
  epochs:
    values: [200, 250, 300]
  l1:
    values: [1, 5, 10, 100, 50, 25]
  l3:
    values: [1, 1.25, 1.5, 2, 5, 10]
  l4:
    values: [0.01, 0.04, 0.0575 , 0.075, 0.1]
  l5:
    values: [0.01, 0.04, 0.06, 0.675, 0.075, 0.1]
